name = "jz"
main = "src/index.js"
compatibility_date = "2025-11-27"

[[d1_databases]]
binding = "DB"
database_name = "jz"
database_id = "f31e6be9-c28c-4068-99f9-450a60383820"

[vars]
JWT_SECRET = "JWT_SECRET"
